version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mailermongo
    restart: unless-stopped
    # environment:
    #  - MONGO_INITDB_ROOT_USERNAME=admin
    #  - MONGO_INITDB_ROOT_PASSWORD=admin1
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
      
  mailer:
    build: ./
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    ports: 
      - "80:80"
       

volumes:
  mongo:
    driver: local