version: "3.7"

services:
 mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    # environment:
    #  - MONGO_INITDB_ROOT_USERNAME=admin
    #  - MONGO_INITDB_ROOT_PASSWORD=admin1
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo:
    driver: local